<!--
	Ivy
	
	Copyright 2017 IS2T. All rights reserved.
	IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org"> 
	<info organisation="com.microej.test" module="mjvmportagevalidation" status="integration" revision="0.1.0">
		<ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-javalib" revision="4.+">
			<ea:property name="test.run.includes.pattern" value="**/_AllTests_*.class"/>
		</ea:build>
	</info>
	
	<configurations defaultconfmapping="default->default;provided->provided">
		<conf name="default" visibility="public" description="Runtime dependencies to other artifacts"/>
		<conf name="provided" visibility="public" description="Compile-time dependencies to APIs provided by the platform"/>
		<conf name="documentation" visibility="public" description="Documentation related to the artifact (javadoc, PDF)"/>
		<conf name="dist" visibility="public" description="Contains extra files like README.md, licenses"/>
		<conf name="source" visibility="public" description="Source code"/>
 		<conf name="test" visibility="private" description="Dependencies for test execution. It is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
	</configurations>

	<publications>
		<!-- keep this empty if no specific artifact to publish -->
	</publications>
	
	<dependencies>
		<!-- 
			Put MicroEJ API dependencies to the "provided->*" configuration
			Other regular runtime dependencies are in the "default" configuration  
		-->
		<dependency conf="provided->*" org="ej.api" name="edc" rev="[1.2.0-RC0,2.0.0-RC0["/>
		
		<!-- 
			Put your project dependencies here. An example of project dependency declaration 
			is provided below:
			
			<dependency org="[org]" name="[otherArtifact]" rev="[M.m.p-RC0,(M+1).0.0-RC0["/>
		-->
		<dependency conf="test->*" org="ej.library.test" name="junit" rev="[1.0.0-RC0,2.0.0-RC0["/>
		
		
	</dependencies>
</ivy-module>
