<?xml version="1.0" encoding="UTF-8"?>
<!--
	IVY
	
	Copyright 2020 MicroEJ Corp. All rights reserved.
	Use of this source code is governed by a BSD-style license that can be found with this software.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:m="http://ant.apache.org/ivy/maven" xmlns:ej="https://developer.microej.com" ej:version="2.0.0"> 

	<info organisation="com.is2t.cc.projects.0176" module="0176_1_edgepro_fs-testsuite" status="integration" revision="1.8.0">
        <ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-testsuite" revision="[2.2.0-RC0,3.0.0-RC0["/>
        <ea:plugin org="com.is2t.easyant.plugins" module="ivy-update" revision="1.+" />
	</info>
    
    <configurations>
    	<conf name="default" />
    	<conf name="provided" />
    	<conf name="build-test" visibility="private" />
    	<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
    </configurations>

    <publications>
    </publications>
    
    <dependencies>
		<dependency changing="true" org="com.microej.pack.fs" name="fs-testsuite" rev="3.0.0"/>
    </dependencies>
</ivy-module>
